---
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - task
      - dependencies
    ignore:
      # We pin @types/node to our minimum supported Node.js version.
      - dependency-name: '@types/node'
      # We only bump this when we want to use newer TypeScript language features in our codebase for development. This does not impact end users as the distributed package contains compiled JavaScript, not TypeScript.
      - dependency-name: 'typescript'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - task
      - dependencies
