---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint-cli:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Run markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.5.0
        with:
          files: .
          config_file: ".markdownlint.yaml"

  test:
    needs: [markdownlint-cli]
    runs-on: ubuntu-latest
    name: Node.js ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run clean
      - run: npm test
      - run: npm run format-check
      - run: npm run build
